# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equiInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100)),
                ('namee', models.CharField(max_length=100)),
                ('temperature', models.IntegerField()),
                ('times', models.CharField(max_length=100)),
                ('errors', models.CharField(max_length=100)),
                ('history', models.TextField()),
                ('states', models.BooleanField(verbose_name=True)),
            ],
        ),
    ]
